### ISSUE TITLE
TODO：20181103讨论内容

### ISSUE THREAD

**Issue by nonoacc** [hongyuhang/shipproject#11]
1 | Textarea占4行，从头顶到尾
2 | 给洪menu初始化、页面提交的action
3 | B.9泊位数据中有JS，要给洪确定各控件ID
4 | 历史数据的表示形式（检索输入项、一览画面都是动态的，还可以跳到照会页）
5 | 历史数据的一览中，序号需要后端处理（在Service里写，需要页号+每页显示数量）
6 看下一个系统的业务

**Comment by hongyuhang** [comment]
解决了textarea独占一行显示，默认显示4行文字的问题

**Comment by nonoacc** [comment]
2ok
3ok
4todo列表，新开一个issue
5 同4
6 11月8号看
